version: '3.8'
services:
  tabbyapi:
    build:
      context: .
      args:
        INSTALL_FSCHAT: "true"  # Set this to "true" or "false" as needed
    ports:
      - "5000:5000"
    environment:
      - NAME=TabbyAPI
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models:/usr/src/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
